--------------------------------------------------------
-- Archivo creado  - lunes-junio-20-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ESTADO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VIALIDADURBANA"."ESTADO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MUNICIPIO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VIALIDADURBANA"."MUNICIPIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PAIS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VIALIDADURBANA"."PAIS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PARADAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VIALIDADURBANA"."PARADAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RUTAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VIALIDADURBANA"."RUTAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USUARIOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VIALIDADURBANA"."USUARIOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CATALOGO
--------------------------------------------------------

  CREATE TABLE "VIALIDADURBANA"."CATALOGO" 
   (	"IDCATALOGO" NUMBER(*,0), 
	"IDCATEGORIA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"ORDEN" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTADO
--------------------------------------------------------

  CREATE TABLE "VIALIDADURBANA"."ESTADO" 
   (	"IDESTADO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"IDPAIS" NUMBER(*,0), 
	"CLAVE" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MUNICIPIO
--------------------------------------------------------

  CREATE TABLE "VIALIDADURBANA"."MUNICIPIO" 
   (	"IDMUNICIPIO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"IDESTADO" NUMBER(*,0), 
	"CLAVE" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAIS
--------------------------------------------------------

  CREATE TABLE "VIALIDADURBANA"."PAIS" 
   (	"IDPAIS" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"CLAVE" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PARADAS
--------------------------------------------------------

  CREATE TABLE "VIALIDADURBANA"."PARADAS" 
   (	"IDPARADA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"LATITUD" FLOAT(126), 
	"LONGITUD" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RUTA_PARADA
--------------------------------------------------------

  CREATE TABLE "VIALIDADURBANA"."RUTA_PARADA" 
   (	"IDRUTA" NUMBER(*,0), 
	"IDPARADA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RUTAS
--------------------------------------------------------

  CREATE TABLE "VIALIDADURBANA"."RUTAS" 
   (	"IDRUTA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"IDESTATUS" NUMBER, 
	"IDEMPRESATRANSPORTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "VIALIDADURBANA"."USUARIOS" 
   (	"IDUSUARIO" NUMBER(*,0), 
	"TIEMPOREGISTRO" DATE, 
	"IDPARADA" NUMBER(*,0), 
	"LATITUD" FLOAT(126), 
	"LONGITUD" FLOAT(126), 
	"IDRUTAESPERA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into VIALIDADURBANA.CATALOGO
SET DEFINE OFF;
REM INSERTING into VIALIDADURBANA.ESTADO
SET DEFINE OFF;
REM INSERTING into VIALIDADURBANA.MUNICIPIO
SET DEFINE OFF;
REM INSERTING into VIALIDADURBANA.PAIS
SET DEFINE OFF;
REM INSERTING into VIALIDADURBANA.PARADAS
SET DEFINE OFF;
REM INSERTING into VIALIDADURBANA.RUTA_PARADA
SET DEFINE OFF;
REM INSERTING into VIALIDADURBANA.RUTAS
SET DEFINE OFF;
REM INSERTING into VIALIDADURBANA.USUARIOS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CATALOGO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIALIDADURBANA"."CATALOGO_PK" ON "VIALIDADURBANA"."CATALOGO" ("IDCATALOGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESTADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIALIDADURBANA"."ESTADO_PK" ON "VIALIDADURBANA"."ESTADO" ("IDESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PAIS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIALIDADURBANA"."PAIS_PK" ON "VIALIDADURBANA"."PAIS" ("IDPAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PARADAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIALIDADURBANA"."PARADAS_PK" ON "VIALIDADURBANA"."PARADAS" ("IDPARADA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RUTA_PARADA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIALIDADURBANA"."RUTA_PARADA_PK" ON "VIALIDADURBANA"."RUTA_PARADA" ("IDRUTA", "IDPARADA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RUTAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIALIDADURBANA"."RUTAS_PK" ON "VIALIDADURBANA"."RUTAS" ("IDRUTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIALIDADURBANA"."TABLE1_PK" ON "VIALIDADURBANA"."MUNICIPIO" ("IDMUNICIPIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIALIDADURBANA"."USUARIOS_PK" ON "VIALIDADURBANA"."USUARIOS" ("IDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CATALOGO
--------------------------------------------------------

  ALTER TABLE "VIALIDADURBANA"."CATALOGO" ADD CONSTRAINT "CATALOGO_PK" PRIMARY KEY ("IDCATALOGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VIALIDADURBANA"."CATALOGO" MODIFY ("ORDEN" NOT NULL ENABLE);
  ALTER TABLE "VIALIDADURBANA"."CATALOGO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VIALIDADURBANA"."CATALOGO" MODIFY ("IDCATALOGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADO
--------------------------------------------------------

  ALTER TABLE "VIALIDADURBANA"."ESTADO" ADD CONSTRAINT "ESTADO_PK" PRIMARY KEY ("IDESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VIALIDADURBANA"."ESTADO" MODIFY ("IDPAIS" NOT NULL ENABLE);
  ALTER TABLE "VIALIDADURBANA"."ESTADO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VIALIDADURBANA"."ESTADO" MODIFY ("IDESTADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MUNICIPIO
--------------------------------------------------------

  ALTER TABLE "VIALIDADURBANA"."MUNICIPIO" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("IDMUNICIPIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VIALIDADURBANA"."MUNICIPIO" MODIFY ("IDESTADO" NOT NULL ENABLE);
  ALTER TABLE "VIALIDADURBANA"."MUNICIPIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VIALIDADURBANA"."MUNICIPIO" MODIFY ("IDMUNICIPIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAIS
--------------------------------------------------------

  ALTER TABLE "VIALIDADURBANA"."PAIS" ADD CONSTRAINT "PAIS_PK" PRIMARY KEY ("IDPAIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VIALIDADURBANA"."PAIS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VIALIDADURBANA"."PAIS" MODIFY ("IDPAIS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARADAS
--------------------------------------------------------

  ALTER TABLE "VIALIDADURBANA"."PARADAS" ADD CONSTRAINT "PARADAS_PK" PRIMARY KEY ("IDPARADA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VIALIDADURBANA"."PARADAS" MODIFY ("LONGITUD" NOT NULL ENABLE);
  ALTER TABLE "VIALIDADURBANA"."PARADAS" MODIFY ("LATITUD" NOT NULL ENABLE);
  ALTER TABLE "VIALIDADURBANA"."PARADAS" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "VIALIDADURBANA"."PARADAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VIALIDADURBANA"."PARADAS" MODIFY ("IDPARADA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RUTA_PARADA
--------------------------------------------------------

  ALTER TABLE "VIALIDADURBANA"."RUTA_PARADA" ADD CONSTRAINT "RUTA_PARADA_PK" PRIMARY KEY ("IDRUTA", "IDPARADA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VIALIDADURBANA"."RUTA_PARADA" MODIFY ("IDPARADA" NOT NULL ENABLE);
  ALTER TABLE "VIALIDADURBANA"."RUTA_PARADA" MODIFY ("IDRUTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RUTAS
--------------------------------------------------------

  ALTER TABLE "VIALIDADURBANA"."RUTAS" MODIFY ("IDEMPRESATRANSPORTE" NOT NULL ENABLE);
  ALTER TABLE "VIALIDADURBANA"."RUTAS" MODIFY ("IDESTATUS" NOT NULL ENABLE);
  ALTER TABLE "VIALIDADURBANA"."RUTAS" ADD CONSTRAINT "RUTAS_PK" PRIMARY KEY ("IDRUTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VIALIDADURBANA"."RUTAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VIALIDADURBANA"."RUTAS" MODIFY ("IDRUTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "VIALIDADURBANA"."USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VIALIDADURBANA"."USUARIOS" MODIFY ("TIEMPOREGISTRO" NOT NULL ENABLE);
  ALTER TABLE "VIALIDADURBANA"."USUARIOS" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CATALOGO
--------------------------------------------------------

  ALTER TABLE "VIALIDADURBANA"."CATALOGO" ADD CONSTRAINT "CATALOGO_FK1" FOREIGN KEY ("IDCATEGORIA")
	  REFERENCES "VIALIDADURBANA"."CATALOGO" ("IDCATALOGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTADO
--------------------------------------------------------

  ALTER TABLE "VIALIDADURBANA"."ESTADO" ADD CONSTRAINT "ESTADO_FK2" FOREIGN KEY ("IDPAIS")
	  REFERENCES "VIALIDADURBANA"."PAIS" ("IDPAIS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MUNICIPIO
--------------------------------------------------------

  ALTER TABLE "VIALIDADURBANA"."MUNICIPIO" ADD CONSTRAINT "MUNICIPIO_FK1" FOREIGN KEY ("IDESTADO")
	  REFERENCES "VIALIDADURBANA"."ESTADO" ("IDESTADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RUTA_PARADA
--------------------------------------------------------

  ALTER TABLE "VIALIDADURBANA"."RUTA_PARADA" ADD CONSTRAINT "RUTA_PARADA_FK1" FOREIGN KEY ("IDRUTA")
	  REFERENCES "VIALIDADURBANA"."RUTAS" ("IDRUTA") ENABLE;
  ALTER TABLE "VIALIDADURBANA"."RUTA_PARADA" ADD CONSTRAINT "RUTA_PARADA_FK2" FOREIGN KEY ("IDPARADA")
	  REFERENCES "VIALIDADURBANA"."PARADAS" ("IDPARADA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RUTAS
--------------------------------------------------------

  ALTER TABLE "VIALIDADURBANA"."RUTAS" ADD CONSTRAINT "RUTAS_FK1" FOREIGN KEY ("IDESTATUS")
	  REFERENCES "VIALIDADURBANA"."CATALOGO" ("IDCATALOGO") ENABLE;
  ALTER TABLE "VIALIDADURBANA"."RUTAS" ADD CONSTRAINT "RUTAS_FK2" FOREIGN KEY ("IDEMPRESATRANSPORTE")
	  REFERENCES "VIALIDADURBANA"."CATALOGO" ("IDCATALOGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "VIALIDADURBANA"."USUARIOS" ADD CONSTRAINT "USUARIOS_FK1" FOREIGN KEY ("IDPARADA")
	  REFERENCES "VIALIDADURBANA"."PARADAS" ("IDPARADA") ENABLE;
  ALTER TABLE "VIALIDADURBANA"."USUARIOS" ADD CONSTRAINT "USUARIOS_FK2" FOREIGN KEY ("IDRUTAESPERA")
	  REFERENCES "VIALIDADURBANA"."RUTAS" ("IDRUTA") ENABLE;
--------------------------------------------------------
--  DDL for Trigger ESTADO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VIALIDADURBANA"."ESTADO_TRG" 
BEFORE INSERT ON ESTADO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDESTADO IS NULL THEN
      SELECT ESTADO_SEQ.NEXTVAL INTO :NEW.IDESTADO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VIALIDADURBANA"."ESTADO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MUNICIPIO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VIALIDADURBANA"."MUNICIPIO_TRG" 
BEFORE INSERT ON MUNICIPIO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDMUNICIPIO IS NULL THEN
      SELECT MUNICIPIO_SEQ.NEXTVAL INTO :NEW.IDMUNICIPIO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VIALIDADURBANA"."MUNICIPIO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PAIS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VIALIDADURBANA"."PAIS_TRG" 
BEFORE INSERT ON PAIS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDPAIS IS NULL THEN
      SELECT PAIS_SEQ.NEXTVAL INTO :NEW.IDPAIS FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VIALIDADURBANA"."PAIS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PARADAS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VIALIDADURBANA"."PARADAS_TRG" 
BEFORE INSERT ON PARADAS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDPARADA IS NULL THEN
      SELECT PARADAS_SEQ.NEXTVAL INTO :NEW.IDPARADA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VIALIDADURBANA"."PARADAS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RUTAS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VIALIDADURBANA"."RUTAS_TRG" 
BEFORE INSERT ON RUTAS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDRUTA IS NULL THEN
      SELECT RUTAS_SEQ.NEXTVAL INTO :NEW.IDRUTA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VIALIDADURBANA"."RUTAS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USUARIOS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VIALIDADURBANA"."USUARIOS_TRG" 
BEFORE INSERT ON USUARIOS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDUSUARIO IS NULL THEN
      SELECT USUARIOS_SEQ.NEXTVAL INTO :NEW.IDUSUARIO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VIALIDADURBANA"."USUARIOS_TRG" ENABLE;
